# Generated by Django 2.0.2 on 2018-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal_verb', models.TextField(max_length=100)),
                ('meaning', models.TextField(max_length=42)),
                ('example', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'verb',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
