# Generated by Django 2.0.2 on 2018-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180215_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='proposition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='example',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='meaning',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='phrasal_verb',
            field=models.CharField(max_length=100),
        ),
    ]
