# Generated by Django 2.0.2 on 2018-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180216_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
