# Generated by Django 2.0.2 on 2018-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_proposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposition',
        ),
    ]
