# Generated by Django 2.0.2 on 2018-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180216_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='proposition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
