# Generated by Django 2.0.2 on 2018-02-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180216_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='proposition',
            field=models.IntegerField(default=0),
        ),
    ]
