# Generated by Django 2.0.2 on 2018-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180218_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
