# Generated by Django 2.0.2 on 2018-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_verb_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal_verb', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=100)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
