# Generated by Django 2.0.2 on 2018-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180220_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='start_with',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='error',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
