# Generated by Django 2.0.2 on 2018-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180221_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereport',
            name='date',
            field=models.FloatField(default=0),
        ),
    ]
