# Generated by Django 2.0.2 on 2018-02-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180221_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereport',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datereport',
            name='success_ratio',
            field=models.IntegerField(default=0),
        ),
    ]
