# Generated by Django 2.0.2 on 2018-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180221_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='datereport',
            name='example',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datereport',
            name='meaning',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datereport',
            name='phrasal_verb',
            field=models.CharField(default='', max_length=100),
        ),
    ]
